site_name: FitLife documentation
theme: readthedocs
markdown_extensions:
  - md_in_html
  # - plantuml_markdown
plugins:
  - search
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/

nav:
  - Home: index.md
  - C4/Context: architecture/context.md