site_name: FitLife documentation
theme: readthedocs
markdown_extensions:
  - md_in_html
  - plantuml_markdown
plugins:
  - search
  - plantuml:
      theme:
        enabled: false
      puml_url: https://www.plantuml.com/plantuml/

nav:
  - Home: index.md